In [3]:
import numpy as np
import pandas as pd
import matplotlib as plot

In [4]:
df=pd.read_csv("C:/Users/ELCOT/Downloads/Europe Sales Records.csv")

In [5]:
df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Europe,Czech Republic,Beverages,Offline,C,9/12/2011,478051030,9/29/2011,4778,47.45,31.79,226716.10,151892.62,74823.48
1,Europe,Bosnia and Herzegovina,Clothes,Online,M,10/14/2013,919133651,11/4/2013,927,109.28,35.84,101302.56,33223.68,68078.88
2,Europe,Austria,Cereal,Offline,C,8/13/2014,987410676,9/6/2014,5616,205.70,117.11,1155211.20,657689.76,497521.44
3,Europe,Bulgaria,Office Supplies,Online,L,10/31/2010,672330081,11/29/2010,6266,651.21,524.96,4080481.86,3289399.36,791082.50
4,Europe,Estonia,Fruits,Online,L,9/28/2016,579463422,11/1/2016,4958,9.33,6.92,46258.14,34309.36,11948.78

In [6]:
df.tail()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
1325,Europe,Norway,Personal Care,Offline,M,1/14/2014,634033286,1/15/2014,3394,81.73,56.67,277391.62,192337.98,85053.64
1326,Europe,Ukraine,Cereal,Offline,L,4/14/2014,559183347,5/21/2014,3633,205.70,117.11,747308.10,425460.63,321847.47
1327,Europe,Armenia,Meat,Offline,M,11/9/2015,781416594,12/23/2015,7390,421.89,364.69,3117767.10,2695059.10,422708.00
1328,Europe,Denmark,Clothes,Offline,H,5/9/2012,713357150,6/3/2012,7088,109.28,35.84,774576.64,254033.92,520542.72
1329,Europe,Finland,Clothes,Online,L,4/22/2014,906794202,5/11/2014,9410,109.28,35.84,1028324.80,337254.40,691070.40

In [7]:
print("Data frame\n",df.columns)

Data frame
 Index(['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority',
       'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price',
       'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit'],
      dtype='str')

In [9]:
print(df["Item Type"])

0             Beverages
1               Clothes
2                Cereal
3       Office Supplies
4                Fruits
             ...
1325      Personal Care
1326             Cereal
1327               Meat
1328            Clothes
1329            Clothes
Name: Item Type, Length: 1330, dtype: str

In [10]:
two_col=[["",""]]

In [11]:
pip install loc

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: loc in .\AppData\Roaming\Python\Python314\site-packages (0.0.2)
Requirement already satisfied: bidict in .\AppData\Roaming\Python\Python314\site-packages (from loc) (0.24.1)
Note: you may need to restart the kernel to use updated packages.

In [12]:
df.loc[0]

Region                    Europe
Country           Czech Republic
Item Type              Beverages
Sales Channel            Offline
Order Priority                 C
Order Date             9/12/2011
Order ID               478051030
Ship Date              9/29/2011
Units Sold                  4778
Unit Price                 47.45
Unit Cost                  31.79
Total Revenue           226716.1
Total Cost             151892.62
Total Profit            74823.48
Name: 0, dtype: object

In [13]:
df.loc[0:4,["Item Type","Region"]]

         Item Type  Region
0        Beverages  Europe
1          Clothes  Europe
2           Cereal  Europe
3  Office Supplies  Europe
4           Fruits  Europe

In [14]:
df.iloc[0]

Region                    Europe
Country           Czech Republic
Item Type              Beverages
Sales Channel            Offline
Order Priority                 C
Order Date             9/12/2011
Order ID               478051030
Ship Date              9/29/2011
Units Sold                  4778
Unit Price                 47.45
Unit Cost                  31.79
Total Revenue           226716.1
Total Cost             151892.62
Total Profit            74823.48
Name: 0, dtype: object

In [17]:
df.iloc[0:5]

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Europe,Czech Republic,Beverages,Offline,C,9/12/2011,478051030,9/29/2011,4778,47.45,31.79,226716.10,151892.62,74823.48
1,Europe,Bosnia and Herzegovina,Clothes,Online,M,10/14/2013,919133651,11/4/2013,927,109.28,35.84,101302.56,33223.68,68078.88
2,Europe,Austria,Cereal,Offline,C,8/13/2014,987410676,9/6/2014,5616,205.70,117.11,1155211.20,657689.76,497521.44
3,Europe,Bulgaria,Office Supplies,Online,L,10/31/2010,672330081,11/29/2010,6266,651.21,524.96,4080481.86,3289399.36,791082.50
4,Europe,Estonia,Fruits,Online,L,9/28/2016,579463422,11/1/2016,4958,9.33,6.92,46258.14,34309.36,11948.78

In [16]:
df.iloc[0:5,0:2]

   Region                 Country
0  Europe          Czech Republic
1  Europe  Bosnia and Herzegovina
2  Europe                 Austria
3  Europe                Bulgaria
4  Europe                 Estonia

In [18]:
df[df["Unit Price"]>100].head(10)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
1,Europe,Bosnia and Herzegovina,Clothes,Online,M,10/14/2013,919133651,11/4/2013,927,109.28,35.84,101302.56,33223.68,68078.88
2,Europe,Austria,Cereal,Offline,C,8/13/2014,987410676,9/6/2014,5616,205.70,117.11,1155211.20,657689.76,497521.44
3,Europe,Bulgaria,Office Supplies,Online,L,10/31/2010,672330081,11/29/2010,6266,651.21,524.96,4080481.86,3289399.36,791082.50
6,Europe,Czech Republic,Cereal,Online,M,7/8/2011,552037513,8/5/2011,9022,205.70,117.11,1855825.40,1056566.42,799258.98
7,Europe,Luxembourg,Vegetables,Offline,L,2/13/2010,744683635,4/1/2010,7291,154.06,90.93,1123251.46,662970.63,460280.83
8,Europe,Switzerland,Meat,Online,L,3/21/2014,169378983,4/10/2014,1860,421.89,364.69,784715.40,678323.40,106392.00
10,Europe,Belgium,Snacks,Online,M,1/12/2015,519380223,1/17/2015,5005,152.58,97.44,763662.90,487687.20,275975.70
11,Europe,San Marino,Office Supplies,Online,H,4/13/2014,904589211,5/4/2014,6905,651.21,524.96,4496605.05,3624848.80,871756.25
12,Europe,Bosnia and Herzegovina,Baby Food,Online,C,4/4/2015,184412229,4/7/2015,531,255.28,159.42,135553.68,84652.02,50901.66
13,Europe,Netherlands,Meat,Offline,M,3/8/2017,747774398,4/3/2017,1916,421.89,364.69,808341.24,698746.04,109595.20

In [19]:
df[df["Sales Channel"].isin(["Offline"])]

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Europe,Czech Republic,Beverages,Offline,C,9/12/2011,478051030,9/29/2011,4778,47.45,31.79,226716.10,151892.62,74823.48
2,Europe,Austria,Cereal,Offline,C,8/13/2014,987410676,9/6/2014,5616,205.70,117.11,1155211.20,657689.76,497521.44
5,Europe,Montenegro,Fruits,Offline,L,5/29/2016,313705861,7/10/2016,1390,9.33,6.92,12968.70,9618.80,3349.90
7,Europe,Luxembourg,Vegetables,Offline,L,2/13/2010,744683635,4/1/2010,7291,154.06,90.93,1123251.46,662970.63,460280.83
13,Europe,Netherlands,Meat,Offline,M,3/8/2017,747774398,4/3/2017,1916,421.89,364.69,808341.24,698746.04,109595.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1323,Europe,Russia,Personal Care,Offline,H,11/12/2011,473845756,12/16/2011,344,81.73,56.67,28115.12,19494.48,8620.64
1325,Europe,Norway,Personal Care,Offline,M,1/14/2014,634033286,1/15/2014,3394,81.73,56.67,277391.62,192337.98,85053.64
1326,Europe,Ukraine,Cereal,Offline,L,4/14/2014,559183347,5/21/2014,3633,205.70,117.11,747308.10,425460.63,321847.47
1327,Europe,Armenia,Meat,Offline,M,11/9/2015,781416594,12/23/2015,7390,421.89,364.69,3117767.10,2695059.10,422708.00
1328,Europe,Denmark,Clothes,Offline,H,5/9/2012,713357150,6/3/2012,7088,109.28,35.84,774576.64,254033.92,520542.72

In [20]:
df[df["Order Priority"]=="M"]

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
1,Europe,Bosnia and Herzegovina,Clothes,Online,M,10/14/2013,919133651,11/4/2013,927,109.28,35.84,101302.56,33223.68,68078.88
6,Europe,Czech Republic,Cereal,Online,M,7/8/2011,552037513,8/5/2011,9022,205.70,117.11,1855825.40,1056566.42,799258.98
10,Europe,Belgium,Snacks,Online,M,1/12/2015,519380223,1/17/2015,5005,152.58,97.44,763662.90,487687.20,275975.70
13,Europe,Netherlands,Meat,Offline,M,3/8/2017,747774398,4/3/2017,1916,421.89,364.69,808341.24,698746.04,109595.20
14,Europe,Russia,Household,Online,M,7/10/2017,194176757,8/20/2017,72,668.27,502.54,48115.44,36182.88,11932.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1315,Europe,Czech Republic,Office Supplies,Offline,M,6/19/2010,885046851,7/19/2010,3886,651.21,524.96,2530602.06,2039994.56,490607.50
1316,Europe,Czech Republic,Vegetables,Online,M,6/14/2012,527079236,6/20/2012,3314,154.06,90.93,510554.84,301342.02,209212.82
1319,Europe,Italy,Household,Offline,M,2/22/2011,677851569,3/2/2011,198,668.27,502.54,132317.46,99502.92,32814.54
1325,Europe,Norway,Personal Care,Offline,M,1/14/2014,634033286,1/15/2014,3394,81.73,56.67,277391.62,192337.98,85053.64
1327,Europe,Armenia,Meat,Offline,M,11/9/2015,781416594,12/23/2015,7390,421.89,364.69,3117767.10,2695059.10,422708.00

In [22]:
df.sort_values("Order ID").head(10)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
30,Europe,Norway,Cereal,Online,M,10/8/2014,100640618,10/18/2014,650,205.70,117.11,133705.00,76121.50,57583.50
1079,Europe,Serbia,Cereal,Offline,C,8/11/2016,100983083,8/11/2016,1993,205.70,117.11,409960.10,233400.23,176559.87
620,Europe,Kosovo,Household,Online,M,7/18/2014,101025998,8/11/2014,4693,668.27,502.54,3136191.11,2358420.22,777770.89
1117,Europe,Montenegro,Clothes,Online,L,5/13/2017,102230632,6/13/2017,1171,109.28,35.84,127966.88,41968.64,85998.24
416,Europe,Serbia,Beverages,Offline,H,8/11/2012,103435266,9/18/2012,7648,47.45,31.79,362897.60,243129.92,119767.68
1227,Europe,Slovakia,Office Supplies,Online,H,3/15/2015,103450715,4/18/2015,2220,651.21,524.96,1445686.20,1165411.20,280275.00
998,Europe,France,Fruits,Online,L,4/20/2013,103499639,6/6/2013,6698,9.33,6.92,62492.34,46350.16,16142.18
433,Europe,Spain,Vegetables,Online,M,11/12/2011,103762280,12/14/2011,4419,154.06,90.93,680791.14,401819.67,278971.47
109,Europe,Croatia,Baby Food,Offline,H,9/19/2012,103832662,10/20/2012,5247,255.28,159.42,1339454.16,836476.74,502977.42
350,Europe,Germany,Cereal,Online,M,1/23/2011,104008615,2/22/2011,7315,205.70,117.11,1504695.50,856659.65,648035.85

In [23]:
df["Total Lose"]=df["Total Cost"]*df["Total Profit"]
df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Total Lose
0,Europe,Czech Republic,Beverages,Offline,C,9/12/2011,478051030,9/29/2011,4778,47.45,31.79,226716.10,151892.62,74823.48,1.136513e+10
1,Europe,Bosnia and Herzegovina,Clothes,Online,M,10/14/2013,919133651,11/4/2013,927,109.28,35.84,101302.56,33223.68,68078.88,2.261831e+09
2,Europe,Austria,Cereal,Offline,C,8/13/2014,987410676,9/6/2014,5616,205.70,117.11,1155211.20,657689.76,497521.44,3.272148e+11
3,Europe,Bulgaria,Office Supplies,Online,L,10/31/2010,672330081,11/29/2010,6266,651.21,524.96,4080481.86,3289399.36,791082.50,2.602186e+12
4,Europe,Estonia,Fruits,Online,L,9/28/2016,579463422,11/1/2016,4958,9.33,6.92,46258.14,34309.36,11948.78,4.099550e+08

In [26]:
df.groupby("Item Type")["Unit Price"].sum()

Item Type
Baby Food          28591.36
Beverages           5741.45
Cereal             21187.10
Clothes            11474.40
Cosmetics          49840.80
Fruits              1044.96
Household          64822.19
Meat               46829.79
Office Supplies    80098.83
Personal Care       9398.95
Snacks             15715.74
Vegetables         17562.84
Name: Unit Price, dtype: float64

In [27]:
df.groupby("Item Type")["Unit Price"].min()

Item Type
Baby Food          255.28
Beverages           47.45
Cereal             205.70
Clothes            109.28
Cosmetics          437.20
Fruits               9.33
Household          668.27
Meat               421.89
Office Supplies    651.21
Personal Care       81.73
Snacks             152.58
Vegetables         154.06
Name: Unit Price, dtype: float64

In [24]:
df.groupby("Product")["Sales"].max()

Product
Headphones     600
Laptop        4800
Smartphone    3200
Smartwatch    1000
Tablet        1800
Name: Sales, dtype: int64

In [26]:
df.groupby("Product")["Sales"].mean()

Product
Headphones     340.909091
Laptop        2784.000000
Smartphone    2523.076923
Smartwatch     762.500000
Tablet        1260.000000
Name: Sales, dtype: float64

In [30]:
df.groupby("Product")["Sales"].count()

Product
Headphones    22
Laptop        25
Smartphone    13
Smartwatch    20
Tablet        20
Name: Sales, dtype: int64

In [29]:
df.describe()

           OrderID    Quantity    UnitPrice        Sales
count   100.000000  100.000000   100.000000   100.000000
mean   1050.500000    2.660000   577.000000  1503.500000
std      29.011492    1.139023   412.213782  1258.712165
min    1001.000000    1.000000   150.000000   150.000000
25%    1025.750000    2.000000   250.000000   450.000000
50%    1050.500000    3.000000   450.000000  1000.000000
75%    1075.250000    4.000000   900.000000  2400.000000
max    1100.000000    4.000000  1200.000000  4800.000000